# Generated by Django 5.2.4 on 2026-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo (opcional)')),
            ],
            options={
                'verbose_name': 'Fecha bloqueada',
                'verbose_name_plural': 'Fechas bloqueadas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario disponible',
                'verbose_name_plural': 'Horarios disponibles',
                'ordering': ['weekday', 'time'],
                'unique_together': {('weekday', 'time')},
            },
        ),
    ]
